openapi: 3.1.0
info:
  title: Template Mng
  description: Api specification for manges customer interactions.
  version: '1.0'
servers:
  - url: https://{gigya-domain}
    variables:
      gigya-domain:
        default: admin.gigya.com
        enum:
          - admin.gigya.com
          - admin.eu1.gigya.com
          - admin.au1.gigya.com
        description: giya domains
paths:
  /interactions/templates:
    $ref: paths\interactions@templates.yaml
  /interactions/templates/{template}:
    $ref: paths\interactions@templates@{template}.yaml


  /subscribtions:
    $ref: paths\subscriptions.yaml 
    
  /subscribtions/{subscriptionId}:
    $ref: paths\subscribtions@{subscriptionId}.yaml

  /subscribtions/{subscriptionId}/fields:
    $ref: paths\subscribtions@{subscriptionId}@fields.yaml

  /template/{subscriptionId}/fields/{fieldId}:
    $ref: paths\subscribtions@{subscriptionId}@fields@{fieldId}.yaml
    
  /subscribtions/{subscriptionId}/fields/channel:
    $ref: paths\subscribtions@{subscriptionId}@fields@channel.yaml
    
    
tags: []
