openapi: 3.1.0
info:
  title: Template Mng
  description: Api specification for manges customer interactions.
  version: '1.0'
servers:
  - url: https://{gigya-domain}
    variables:
      gigya-domain:
        default: admin.gigya.com
        enum:
          - admin.gigya.com
          - admin.eu1.gigya.com
          - admin.au1.gigya.com
        description: giya domains
paths:
  /interactions/templates:
    $ref: paths\interactions@templates.yaml
  /interactions/templates/{template}:
    $ref: paths\interactions@templates@{template}.yaml
  /subscribtions/{subscriptionId}/fields/channel:
    $ref: paths\template@{subscriptionId}@fields@channel.yaml
tags: []
